### ISSUE TITLE
Test ping

### ISSUE THREAD

**Issue by Lahbak** [LABORA-INF-UFG/NetSoft2020-Tutorial4-Demo2-Exp1#3]
HI Team,
I installed this Demo but i have a problem with test connectivity with the internet
root@9667c28ee356:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.187.3.254  netmask 255.255.255.0  broadcast 192.187.3.255
        ether 02:42:c0:bb:03:fe  txqueuelen 0  (Ethernet)
        RX packets 390559  bytes 41206503 (41.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 131735  bytes 18081517 (18.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 18  bytes 1376 (1.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1376 (1.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

oaitun_ue1: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 45.45.0.2  netmask 255.0.0.0  destination 45.45.0.2
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
.
.
oaitun_ue3: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 45.45.0.3  netmask 255.0.0.0  destination 45.45.0.3
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2780  bytes 233520 (233.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@9667c28ee356:~# ping google.com
PING google.com (172.217.171.206) 56(84) bytes of data.
64 bytes from google.com (172.217.171.206): icmp_seq=1 ttl=127 time=56.5 ms
64 bytes from google.com (172.217.171.206): icmp_seq=2 ttl=127 time=59.0 ms
64 bytes from google.com (172.217.171.206): icmp_seq=3 ttl=127 time=52.2 ms
64 bytes from google.com (172.217.171.206): icmp_seq=4 ttl=127 time=51.8 ms

and when I do : 
**root@9667c28ee356:~# ping google.com -I 45.45.0.3
PING google.com (172.217.171.206) from 45.45.0.3 : 56(84) bytes of data.**
.
this doesn't work
can you help me please for this issue ?
Thank you so much,

**Comment by Shaligram** [comment]
Hi, 
I followed the exact steps mentioned for NetSoft2020-Tutorial4-Demo2-Exp1. My dockers are all coming up but the ping from UE is not going through. I see the enb process has died. 

Can you point out what could be issue.
I am running on VM with 2 core 4GB RAM, Ubunut 18.04, x_86_64.
I verified all other processes are running fine on other dockers. 

```

[NFAPI_VNF]   PNF to VNF phy_id:1 adjustment0 phy->previous_sf_offset_filtered:-180 phy->previous_sf_offset_filtered:-180 phy->sf_offset_trend:190
[SCTP]   Found data for descriptor 86
[SCTP]   [7][86] Msg of length 7 received from port 36412, on stream 0, PPID 18
[S1AP]   Unknown procedure ID (35) for initiating message

Assertion (0) failed!
In s1ap_eNB_decode_initiating_message() /root/enb/openair3/S1AP/s1ap_eNB_decoder.c:93
Unknown procedure ID (35) for initiating message

Exiting execution
root@21d3055c6ec6:~#                

```

**Comment by EmanueleGallone** [comment]
Hi,

I have the same problem. Ping does not work from UEs. Can you explain how did you solve this issue?

**Comment by Lahbak** [comment]
I have not resolved the issue but what I observed is that the ping worked
temporary then it's stopped.

**Comment by Shaligram** [comment]
Hi,

I think it has to be do with "enb" process getting killed. you can check inside end docker via ps -ef. The reason to it is not quite clear.

one thing I noticed is when I ran on VM with low configuration like only 4 cores. It always crashes. 

_I moved the installation to VM with 10 cores & 16GB RAM, it was all working fine_ for long time with intermittent crash again in ENB process. so, may be there are two issue - related to CPU affinity requiring more number of core, probably 1 cpu core per docker process OR be there is subtle bug on ENB process leading to crash.
